# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "ctrl-dns"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ctrl-dns"
test = true
bench = false
path = "src/main.rs"

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
ntex = { version = "0.6.5", features = ["tokio"] }
nanocld_client = "0.4.0"
futures = "0.3.26"
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.94"
