[package]
name = "ncvpnkit"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
dev = ["nanocl_utils/dev"]
test = []

[build-dependencies]
nanocl_utils = { version = "0.3.1", features = ["build_tools"] }

[dependencies]
log = "0.4.20"
futures-util = "0.3.28"
ntex = { version = "0.7.12", features = ["tokio"] }
vpnkitrc = { version = "0.1.2", features = ["tokio"] }
nanocld_client = { version = "0.12.0" }
nanocl_utils = { version = "0.3.1", features = ["logger"] }
serde_json = "1.0.108"
nanocl_error = { version = "0.1.1", features = [
  "io",
  "http_client",
  "serde_json",
] }
