[workspace]
members = [
  "cli",
  "daemon",
  "models"
]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[patch.crates-io]
nanocl-models = { path = "models" }
bollard = { git = "https://github.com/leon3s/bollard" }
