[workspace]
members = [
  "crates/nanocl_stubs",
  "crates/nanocld_client",
  "bin/nanocld",
  "bin/nanocl"
]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = "debuginfo"

[patch.crates-io]
nanocl_stubs = { path = "crates/nanocl_stubs" }
nanocld_client = { path = "crates/nanocld_client" }
ntex = { git = "https://github.com/ntex-rs/ntex" }
ntex-tokio = { git = "https://github.com/ntex-rs/ntex" }
