[workspace]
members = [
  "models",
  "client",
  "daemon",
  "cli",
]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[patch.crates-io]
nanocl-models = { path = "models" }
nanocl-client = { path = "client" }
bollard = { git = "https://github.com/leon3s/bollard" }
