[workspace]
members = [
  "crates/nanocl_stubs",
  "crates/nanocld_client",
  "bin/nanocld",
  "bin/nanocl"
]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[patch.crates-io]
nanocl_stubs = { path = "crates/nanocl_stubs" }
nanocld_client = { path = "crates/nanocld_client" }
ntex-multipart = { git = "https://github.com/ntex-rs/ntex-extras.git" }
