version: '3.9'

networks:
  system:
    name: system
    driver: bridge
    external: false
    driver_opts:
      com.docker.network.bridge.name: nanocl.system

services:
  nstore:
    container_name: nstore.system.c
    hostname: nstore.nanocl.internal
    image: cockroachdb/cockroach:v23.1.4
    tty: true
    ports:
      - 26257:26257
    networks:
      - system
    volumes:
      - ${STATE_DIR:-${HOME}/.nanocl/state/store/ca}:/ca
      - ${STATE_DIR:-${HOME}/.nanocl/state/store/certs}:/certs
      - ${STATE_DIR:-${HOME}/.nanocl/state/store/data}:/cockroach/cockroach-data
    environment:
      - TZ=Europe/Paris
    command:
      - start-single-node
      - --insecure
      - --listen-addr=:26257
    labels:
      - io.nanocl=enabled
      - io.nanocl.c=nstore.system
      - io.nanocl.n=system
      - io.nanocl.cnsp=system

  nmetrics:
    container_name: nmetrics.system.c
    image: ghcr.io/nxthat/metrsd:0.3.0
    tty: true
    networks:
      - system
    environment:
      - TZ=Europe/Paris
      - LOG_LEVEL=metrsd=info
    command:
      - --hosts
      - unix:///run/nanocl/metrics.sock
    labels:
      - io.nanocl=enabled
      - io.nanocl.c=nmetrics.system
      - io.nanocl.n=system
      - io.nanocl.cnsp=system
    volumes:
      - ${STATE_DIR:-${HOME}/.nanocl/run}:/run/nanocl

  nproxy:
    container_name: nproxy.system.c
    image: nproxy:dev
    tty: true
    network_mode: host
    environment:
      - TZ=Europe/Paris
    labels:
      - io.nanocl=enabled
      - io.nanocl.c=nproxy.system
      - io.nanocl.n=system
      - io.nanocl.cnsp=system
    volumes:
      - ${RUN_DIR:-${HOME}/.nanocl/run}:/run/nanocl
      - ${STATE_DIR:-${HOME}/.nanocl/state/proxy/letsencrypt}:/etc/letsencrypt
      - ${STATE_DIR:-${HOME}/.nanocl/state/proxy/certs}:/etc/nginx/certs
      - ${STATE_DIR:-${HOME}/.nanocl/state/proxy/logs}:/var/log/nginx/access
      - ${STATE_DIR:-${HOME}/.nanocl/state/proxy/html}:/usr/share/nginx/html
      - ${STATE_DIR:-${HOME}/.nanocl/state/proxy/conf.d}:/etc/nginx/conf.d
      - ${STATE_DIR:-${HOME}/.nanocl/state/proxy/sites-enabled}:/etc/nginx/sites-enabled
      - ${STATE_DIR:-${HOME}/.nanocl/state/proxy/streams-enabled}:/etc/nginx/streams-enabled

  ncdproxy:
    container_name: ncdproxy.system.c
    image: ghcr.io/nxthat/nanocl-dev:dev
    tty: true
    ports:
      - 8686:8686
    networks:
      - system
    environment:
      - TZ=Europe/Paris
    command:
      - watch
      - -w
      - /project/bin/ncdproxy/src
      - -x
      - run --no-default-features --features dev --bin ncdproxy
    labels:
      - io.nanocl=enabled
      - io.nanocl.c=ncdproxy.system
      - io.nanocl.n=system
      - io.nanocl.cnsp=system
    volumes:
      - ./:/project
      - ~/.cargo/registry:/usr/local/cargo/registry
      - ${RUN_DIR:-${HOME}/.nanocl/run}:/run/nanocl
      - ${STATE_DIR:-${HOME}/.nanocl/state/proxy/logs}:/var/log/nginx/access
      - ${STATE_DIR:-${HOME}/.nanocl/state/proxy/conf.d}:/etc/nginx/conf.d
      - ${STATE_DIR:-${HOME}/.nanocl/state/proxy/sites-enabled}:/etc/nginx/sites-enabled
      - ${STATE_DIR:-${HOME}/.nanocl/state/proxy/streams-enabled}:/etc/nginx/streams-enabled

  ndns:
    container_name: ndns.system.c
    image: ndns:dev
    tty: true
    network_mode: host
    environment:
      - TZ=Europe/Paris
    labels:
      - io.nanocl=enabled
      - io.nanocl.c=ndns.system
      - io.nanocl.n=system
      - io.nanocl.cnsp=system
    volumes:
      - ${STATE_DIR:-${HOME}/.nanocl/state/dns}:/opt/dns

  ncddns:
    container_name: ncddns.system.c
    image: ghcr.io/nxthat/nanocl-dev:dev
    tty: true
    ports:
      - 8787:8787
    networks:
      - system
    environment:
      - TZ=Europe/Paris
    command:
      - watch
      - -w
      - /project/bin/ncddns/src
      - -x
      - run --no-default-features --features dev --bin ncddns -- --conf-dir /opt/dns
    labels:
      - io.nanocl=enabled
      - io.nanocl.c=ncddns.system
      - io.nanocl.n=system
      - io.nanocl.cnsp=system
    volumes:
      - ./:/project
      - ${STATE_DIR:-${HOME}/.nanocl/state/dns}/dns:/opt/dns
      - ${RUN_DIR:-${HOME}/.nanocl/run}:/run/nanocl
      - ~/.cargo/registry:/usr/local/cargo/registry

  nanocld:
    container_name: ndaemon.system.c
    image: ghcr.io/nxthat/nanocl-dev:dev
    tty: true
    hostname: ndaemon.nanocl.internal
    networks:
      - system
    ports:
      - 8585:8585
    environment:
      - TZ=Europe/Paris
    labels:
      - io.nanocl=enabled
      - io.nanocl.c=ndaemon.system
      - io.nanocl.n=system
      - io.nanocl.cnsp=system
    volumes:
      - ./:/project
      - ~/.cargo/registry:/usr/local/cargo/registry
      - ${STATE_DIR:-${HOME}/.nanocl/state}:/var/lib/nanocl
      - ${RUN_DIR:-${HOME}/.nanocl/run}:/run/nanocl
      - //var/run/docker.sock:/run/docker.sock
    command:
      - watch
      - -w
      - /project/bin/nanocld/src
      - -x
      - run --no-default-features --features dev --bin nanocld -- --gid 1001
