[config]
default_to_workspace = false

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.run-daemon]
command = "cargo"
args = ["run", "--bin", "nanocld"]

[tasks.cov-ci]
command = "cargo"
args = ["llvm-cov", "nextest", "--all", "--output-path", "./lcov.info", "--lcov"]

[tasks.cov]
command = "cargo"
args = ["llvm-cov", "nextest", "--all"]

[tasks.test-daemon]
command = "cargo"
args = ["nextest", "run", "-p", "nanocld"]

[tasks.test-debug]
command = "cargo"
args = ["test", "--", "--nocapture"]

[tasks.test]
command = "cargo"
args = ["nextest", "run"]

[tasks.release]
command = "cargo"
args = ["build", "--release"]
