[config]
default_to_workspace = false

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

# Clean dependencies and build cache
[tasks.clean]
command = "cargo"
args = ["clean"]

# Run daemon
[tasks.run-daemon]
command = "cargo"
args = ["run", "--bin", "nanocld", "${@}"]

# Run cli
[tasks.run-cli]
command = "cargo"
args = ["run", "--bin", "nanocl", "${@}"]

# Test daemon
[tasks.test-daemon]
command = "cargo"
args = ["nextest", "run", "-p", "nanocld"]

# Test Cli
[tasks.test-cli]
command = "cargo"
args = ["nextest", "run", "-p", "nanocl"]

# Test all
[tasks.test]
command = "cargo"
args = [
  "nextest",
  "run",
  "--no-default-features",
  "--features",
  "test",
  "-j",
  "1",
]

# Test all with debug output
[tasks.test-debug]
command = "cargo"
args = [
  "nextest",
  "run",
  "--no-default-features",
  "--features",
  "test",
  "-j",
  "1",
  "--nocapture",
]

[tasks.dev]
command = "docker"
args = ["compose", "up"]

# Test coverage
[tasks.cov]
command = "cargo"
args = [
  "llvm-cov",
  "nextest",
  "--no-default-features",
  "--features",
  "test",
  "-j",
  "1",
]

# Test all with coverage for codecov
[tasks.covgen]
command = "cargo"
args = [
  "llvm-cov",
  "nextest",
  "--no-default-features",
  "--features",
  "test",
  "-j",
  "1",
  "--output-path",
  "./lcov.info",
  "--lcov",
]

# Release
[tasks.release]
command = "cargo"
args = ["build", "--release"]
