[config]
default_to_workspace = false

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

# Clean dependencies and build cache
[tasks.clean]
command = "cargo"
args = ["clean"]

# Run daemon
[tasks.run-daemon]
command = "cargo"
args = ["run", "--bin", "nanocld", "${@}"]

# Run cli
[tasks.run-cli]
command = "cargo"
args = [
  "run",
  "--no-default-features",
  "--features",
  "dev",
  "--bin",
  "nanocl",
  "${@}",
]

# Test daemon
[tasks.tests-daemon]
command = "sh"
args = [
  "scripts/runner.sh",
  "test",
  "--no-default-features",
  "--features",
  "test",
  "${@}",
  "--bin",
  "nanocld",
  "--",
  "--test-threads",
  "1",
]

# Test nanocld_client
[tasks.tests-client]
command = "sh"
args = [
  "scripts/runner.sh",
  "test",
  "--no-default-features",
  "--features",
  "test",
  "${@}",
  "-p",
  "nanocld_client",
  "--",
  "--test-threads",
  "1",
]

# Test Cli
[tasks.tests-cli]
command = "sh"
args = [
  "scripts/runner.sh",
  "test",
  "--no-default-features",
  "--features",
  "test",
  "${@}",
  "--bin",
  "nanocl",
  "--",
  "--test-threads",
  "1",
]

# Test ncdns
[tasks.tests-ncdns]
command = "sh"
args = [
  "scripts/runner.sh",
  "test",
  "--no-default-features",
  "--features",
  "test",
  "${@}",
  "--bin",
  "ncdns",
  "--",
  "--test-threads",
  "1",
]

# Test ncproxy
[tasks.tests-ncproxy]
command = "sh"
args = [
  "scripts/runner.sh",
  "test",
  "--no-default-features",
  "--features",
  "test",
  "${@}",
  "--bin",
  "ncproxy",
  "--",
  "--test-threads",
  "1",
]

# Test all
[tasks.tests]
command = "sh"
args = [
  "scripts/runner.sh",
  "test",
  "--no-default-features",
  "--features",
  "test",
  "--all",
  "${@}",
  "--",
  "--test-threads",
  "1",
]

# Test all with debug output
[tasks.tests-debug]
command = "cargo"
args = ["test", "--no-default-features", "--features", "test", "--nocapture"]

[tasks.dev]
command = "cargo"
args = [
  "make",
  "run-cli",
  "install",
  "--state-dir",
  "${HOME}/.nanocl_dev",
  "-ft",
  "./Statefile.yml",
]

# Test coverage
[tasks.cov]
command = "sh"
args = [
  "scripts/runner.sh",
  "llvm-cov",
  "--all",
  "--no-default-features",
  "--features",
  "test",
  "--output-path",
  "./lcov.info",
  "--lcov",
  "--",
  "--test-threads",
  "1",
]

# Test all with coverage for codecov
[tasks.covgen]
command = "sh"
args = [
  "scripts/runner.sh",
  "llvm-cov",
  "--all",
  "--no-default-features",
  "--features",
  "test",
  "--html",
  "--",
  "--test-threads",
  "1",
]

[tasks.covgenci]
command = "sh"
args = [
  "scripts/runnerci.sh",
  "llvm-cov",
  "--all",
  "--no-default-features",
  "--features",
  "test",
  "--output-path",
  "./lcov.info",
  "--lcov",
  "--",
  "--test-threads",
  "1",
]

# Release
[tasks.release]
command = "cargo"
args = ["build", "--release"]
