# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "ncddns"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ncddns"
test = true
bench = false
path = "src/main.rs"

[dev-dependencies]
serde_yaml = "0.9.19"

[dependencies]
log = "0.4.17"
clap = { version = "4.1.4", features = ["derive"] }
ntex = { version = "0.6.5", features = ["tokio"] }
tokio = { version = "1.23.1", features = ["fs"] }
futures = "0.3.26"
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.94"
nanocld_client = "0.5.0"
nanocl_utils = { version = "0.1.0", features = [
  "logger",
  "io_error",
  "http_error",
  "serde_json",
] }
