openapi: 3.0.3
info:
  title: ncdproxy
  description: Official nanocl controller daemon proxy
  contact:
    name: nanocl contributors
    email: team@next-hat.com
  license:
    name: MIT OR Apache-2.0
  version: 0.3.0
paths:
  /rules/{Name}:
    put:
      tags:
      - Rules
      summary: Create/Update a new ProxyRule
      description: Create/Update a new ProxyRule
      operationId: apply_rule
      parameters:
      - name: Name
        in: path
        description: Name of the rule
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceProxyRule'
        required: true
      responses:
        '200':
          description: List of namespace
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceProxyRule'
    delete:
      tags:
      - Rules
      summary: Delete a ProxyRule
      description: Delete a ProxyRule
      operationId: remove_rule
      parameters:
      - name: Name
        in: path
        description: Name of the rule
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ProxyRule has been deleted
components:
  schemas:
    CargoTarget:
      type: object
      description: Defines a proxy rule target
      required:
      - Key
      - Port
      properties:
        Key:
          type: string
          description: The cargo key
        Port:
          type: integer
          format: int32
          description: The cargo port
          minimum: 0.0
    HttpTarget:
      type: object
      required:
      - Url
      properties:
        Url:
          type: string
          description: Url to target
        Redirect:
          allOf:
          - $ref: '#/components/schemas/UrlRedirect'
          nullable: true
    LocationTarget:
      oneOf:
      - type: object
        required:
        - Cargo
        properties:
          Cargo:
            $ref: '#/components/schemas/CargoTarget'
      - type: object
        required:
        - Http
        properties:
          Http:
            $ref: '#/components/schemas/HttpTarget'
      - type: object
        required:
        - Unix
        properties:
          Unix:
            type: string
            description: Target a specific unix socket
    ProxyHttpLocation:
      type: object
      description: Defines a proxy rule location
      required:
      - Path
      - Target
      properties:
        Path:
          type: string
          description: The path
        Target:
          $ref: '#/components/schemas/LocationTarget'
    ProxyRule:
      oneOf:
      - type: array
        items:
          $ref: '#/components/schemas/ProxyRuleHttp'
      - type: array
        items:
          $ref: '#/components/schemas/ProxyRuleStream'
      description: Proxy rules modes
    ProxyRuleHttp:
      type: object
      description: Defines a proxy rule http config
      required:
      - Network
      - Locations
      properties:
        Domain:
          type: string
          description: The domain
          nullable: true
        Network:
          type: string
          description: Type of private | public | internal | namespace:$namespace_name
        Locations:
          type: array
          items:
            $ref: '#/components/schemas/ProxyHttpLocation'
          description: The locations to handle multiple paths
        Ssl:
          allOf:
          - $ref: '#/components/schemas/ProxySslConfig'
          nullable: true
        Includes:
          type: array
          items:
            type: string
          description: Path to extra config file to include
          nullable: true
    ProxyRuleStream:
      type: object
      description: Proxy rules modes
      required:
      - Network
      - Protocol
      - Port
      - Target
      properties:
        Network:
          type: string
          description: Type of the network binding private | public | internal | namespace:$namespace_name
        Protocol:
          $ref: '#/components/schemas/ProxyStreamProtocol'
        Port:
          type: integer
          format: int32
          description: The port to open on nodes
          minimum: 0.0
        Ssl:
          allOf:
          - $ref: '#/components/schemas/ProxySslConfig'
          nullable: true
        Target:
          $ref: '#/components/schemas/StreamTarget'
    ProxySslConfig:
      type: object
      required:
      - Certificate
      - CertificateKey
      properties:
        Certificate:
          type: string
          description: Path to the certificate
        CertificateKey:
          type: string
          description: Path to the certificate key
        DhParam:
          type: string
          description: Path to the dhparam file
          nullable: true
    ProxyStreamProtocol:
      type: string
      description: Proxy rules modes
      enum:
      - Tcp
      - Udp
    ResourceProxyRule:
      type: object
      description: Define proxy rules to apply
      required:
      - Watch
      - Rules
      properties:
        Watch:
          type: array
          items:
            type: string
          description: Cargo to watch for changes
        Rules:
          $ref: '#/components/schemas/ProxyRule'
    StreamTarget:
      oneOf:
      - type: object
        required:
        - Cargo
        properties:
          Cargo:
            $ref: '#/components/schemas/CargoTarget'
      - type: object
        required:
        - Uri
        properties:
          Uri:
            $ref: '#/components/schemas/UriTarget'
      - type: object
        required:
        - Unix
        properties:
          Unix:
            type: string
            description: Target a specific unix socket
    UriTarget:
      type: object
      required:
      - Uri
      properties:
        Uri:
          type: string
          description: Uri to target
    UrlRedirect:
      type: string
      enum:
      - MovedPermanently
      - PermanentRedirect
      - TemporaryRedirect
tags:
- name: Rules
  description: Rules management endpoints.
