ApiVersion = "v0.12"

Namespace = "global"

[[Cargoes]]
Name = "deploy-example"

[Cargoes.Container]
Image = "ghcr.io/next-hat/nanocl-get-started:latest"
Env = ["APP=GET_STARTED1"]

[[Cargoes]]
Name = "deploy-example2"

[Cargoes.Container]
Image = "ghcr.io/next-hat/nanocl-get-started:latest"
Env = ["APP=GET_STARTED2"]


[[Resources]]
Name = "deploy-example.com"
Kind = "ncproxy.io/rule"

[[Resources.Data.Rules]]
Domain = "deploy-example.com"
Network = "Public"

[[Resources.Data.Rules.Locations]]
Path = "/"

[Resources.Data.Rules.Locations.Target]
Key = "deploy-example2.global.c"
Port = 9_000

[[Resources.Data.Rules.Locations]]
Path = "/v1"

[Resources.Data.Rules.Locations.Target]
Key = "deploy-example.global.c"
Port = 9_000

[[Resources.Data.Rules.Locations]]
Path = "/v2"

[Resources.Data.Rules.Locations.Target]
Key = "deploy-example2.global.c"
Port = 9_000
