openapi: 3.0.3
info:
  title: Nanocl Controller Daemon Dns
  description: |
    The `Nanocl Controller Daemon Dns` is an `HTTP REST API`.<br />
    It is the `API` the `Nanocl Daemon` uses, to create / update and delete `DnsRule`

    ## OpenAPI Specification
    This API is documented in **OpenAPI format** using [Utoipa](https://github.com/juhaku/utoipa)<br />
    The specification is generated automatically when running in development only.<br />
    When releasing a version, the generated file is transfered to our [Documentation](https://github.com/nxthat/documentation).


    ## Cross-Origin Resource Sharing
    This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with  [W3C spec](https://www.w3.org/TR/cors/).<br />
    And that allows cross-domain communication from the browser.<br />
    All responses have a wildcard same-origin which makes them completely public and accessible to everyone, including any code on any site.
  license:
    name: ''
  version: v0.1.1
servers:
- url: /{Version}
  variables:
    Version:
      default: v0.1
      description: API version
      enum:
      - v0.1
paths:
  /_ping:
    head:
      tags:
      - System
      summary: Get version information
      description: Get version information
      operationId: head_ping
      responses:
        '202':
          description: Server is up
  /rules/{Name}:
    put:
      tags:
      - Rules
      summary: Create/Update a new DnsRule
      description: Create/Update a new DnsRule
      operationId: apply_rule
      parameters:
      - name: Name
        in: path
        description: Name of the rule
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceDnsRule'
        required: true
      responses:
        '200':
          description: The created rule
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceDnsRule'
    delete:
      tags:
      - Rules
      summary: Delete a ProxyRule
      description: Delete a ProxyRule
      operationId: remove_rule
      parameters:
      - name: Name
        in: path
        description: Name of the rule
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Rule has been deleted
  /version:
    get:
      tags:
      - System
      summary: Get version information
      description: Get version information
      operationId: get_version
      responses:
        '200':
          description: Version information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
components:
  schemas:
    DnsEntry:
      type: object
      required:
      - Name
      - IpAddress
      properties:
        Name:
          type: string
        IpAddress:
          type: string
    ResourceDnsRule:
      type: object
      required:
      - Network
      - Entries
      properties:
        Network:
          type: string
        Entries:
          type: array
          items:
            $ref: '#/components/schemas/DnsEntry'
    Version:
      type: object
      description: Version contain details about the current version nanocl
      required:
      - Arch
      - Channel
      - Version
      - CommitId
      properties:
        Arch:
          type: string
        Channel:
          type: string
        Version:
          type: string
        CommitId:
          type: string
tags:
- name: Rules
  description: Rules management endpoints.
- name: System
  description: System management endpoints.
