openapi: 3.1.0
info:
  title: Nanocl Controller Proxy
  description: |
    The `Nanocl Controller Proxy` is an `HTTP REST API`.<br />
    It is the `API` the `Nanocl Daemon` uses, to create / update and delete `ncproxy.io/rule`

    ## OpenAPI Specification
    This API is documented in **OpenAPI format** using [Utoipa](https://github.com/juhaku/utoipa)<br />
    The specification is generated automatically when running in development only.<br />
    When releasing a version, the generated file is transferred to our [Documentation](https://github.com/next-hat/documentation).


    ## Cross-Origin Resource Sharing
    This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with  [W3C spec](https://www.w3.org/TR/cors/).<br />
    And that allows cross-domain communication from the browser.<br />
    All responses have a wildcard same-origin which makes them completely public and accessible to everyone, including any code on any site.
  contact:
    name: nanocl contributors
    email: team@next-hat.com
  license:
    name: MIT OR Apache-2.0
  version: v0.13.1
servers:
- url: /{Version}
  variables:
    Version:
      default: v0.14
      description: API version
      enum:
      - v0.13
paths:
  /rules/{name}:
    put:
      tags:
      - Rules
      summary: Create/Update a new ProxyRule
      operationId: apply_rule
      parameters:
      - name: name
        in: path
        description: Name of the rule
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceProxyRule'
        required: true
      responses:
        '200':
          description: The created rule
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceProxyRule'
    delete:
      tags:
      - Rules
      summary: Delete a ProxyRule
      operationId: remove_rule
      parameters:
      - name: name
        in: path
        description: Name of the rule
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Rule has been deleted
components:
  schemas:
    HttpTarget:
      type: object
      required:
      - Url
      properties:
        Url:
          type: string
          description: Url to target
        Redirect:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/UrlRedirect'
            description: Redirect type if it's a redirect
      additionalProperties: false
    LimitReq:
      type: object
      required:
      - Burst
      properties:
        Burst:
          type: integer
          description: The burst size
          minimum: 0
        Delay:
          type:
          - integer
          - 'null'
          description: The delay to wait before retrying
          minimum: 0
      additionalProperties: false
    LimitReqZone:
      type: object
      required:
      - Size
      - Rate
      properties:
        Size:
          type: integer
          description: The max size of the cache in megabytes
          minimum: 0
        Rate:
          type: integer
          description: The max number of request per second
          minimum: 0
      additionalProperties: false
    LocationTarget:
      oneOf:
      - $ref: '#/components/schemas/UpstreamTarget'
        description: Target an existing cargo
      - $ref: '#/components/schemas/HttpTarget'
        description: Target a specific http url
      - $ref: '#/components/schemas/UnixTarget'
        description: Target a specific unix socket
    NetworkKind:
      oneOf:
      - type: string
        description: All networks
        enum:
        - All
      - type: string
        description: Only 127.0.0.1
        enum:
        - Local
      - type: string
        description: Only public ip addresses
        enum:
        - Public
      - type: string
        description: Only internal ip addresses
        enum:
        - Internal
      - type: object
        description: Specific ip address
        required:
        - Other
        properties:
          Other:
            type: string
            description: Specific ip address
      description: Network binding kinds
    ProxyHttpLocation:
      type: object
      description: Defines a proxy rule location
      required:
      - Path
      - Target
      properties:
        Path:
          type: string
          description: The path
        Target:
          $ref: '#/components/schemas/LocationTarget'
          description: The target cargo
        LimitReq:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/LimitReq'
            description: Setup limit request for this location
        AllowedIps:
          type:
          - array
          - 'null'
          items:
            type: string
          description: Allowed ip addr
        Headers:
          type:
          - array
          - 'null'
          items:
            type: string
          description: Extras header to add
        Version:
          type:
          - number
          - 'null'
          format: double
          description: Http version to use
      additionalProperties: false
    ProxyRule:
      oneOf:
      - $ref: '#/components/schemas/ProxyRuleHttp'
        description: Redirect http traffic
      - $ref: '#/components/schemas/ProxyRuleStream'
        description: Redirect tcp and udp traffic
      description: Proxy rules modes
    ProxyRuleHttp:
      type: object
      description: Defines a proxy rule http config
      required:
      - Network
      - Locations
      properties:
        Domain:
          type:
          - string
          - 'null'
          description: The domain
        Port:
          type:
          - integer
          - 'null'
          format: int32
          description: Port to listen on (default 80 or 443)
          minimum: 0
        Network:
          $ref: '#/components/schemas/NetworkKind'
          description: Type of network binding
        LimitReqZone:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/LimitReqZone'
            description: Optional limit request zone
        Locations:
          type: array
          items:
            $ref: '#/components/schemas/ProxyHttpLocation'
          description: The locations to handle multiple paths
        Ssl:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/ProxySsl'
            description: The ssl configuration
        Includes:
          type:
          - array
          - 'null'
          items:
            type: string
          description: Path to extra config file to include
      additionalProperties: false
    ProxyRuleStream:
      type: object
      description: Proxy rules modes
      required:
      - Network
      - Protocol
      - Port
      - Target
      properties:
        Network:
          $ref: '#/components/schemas/NetworkKind'
          description: Type of the network binding
        Protocol:
          $ref: '#/components/schemas/ProxyStreamProtocol'
          description: Protocol to use Tcp | Udp
        Port:
          type: integer
          format: int32
          description: The port to open on nodes
          minimum: 0
        Ssl:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/ProxySsl'
            description: The ssl configuration
        Target:
          $ref: '#/components/schemas/StreamTarget'
          description: The target
      additionalProperties: false
    ProxySsl:
      oneOf:
      - $ref: '#/components/schemas/ProxySslConfig'
      - type: string
    ProxySslConfig:
      type: object
      required:
      - Certificate
      - CertificateKey
      properties:
        Certificate:
          type: string
          description: Path to the certificate
        CertificateKey:
          type: string
          description: Path to the certificate key
        CertificateClient:
          type:
          - string
          - 'null'
          description: Path to the certificate client
        VerifyClient:
          type:
          - boolean
          - 'null'
          description: Enable or disable client verification
        Dhparam:
          type:
          - string
          - 'null'
          description: Path to the dhparam file
      additionalProperties: false
    ProxyStreamProtocol:
      type: string
      description: Proxy rules modes
      enum:
      - Tcp
      - Udp
    ResourceProxyRule:
      type: object
      description: Define proxy rules to apply
      required:
      - Rules
      properties:
        Rules:
          type: array
          items:
            $ref: '#/components/schemas/ProxyRule'
          description: The rules to apply
      additionalProperties: false
    StreamTarget:
      oneOf:
      - $ref: '#/components/schemas/UpstreamTarget'
        description: Target an existing cargo
      - $ref: '#/components/schemas/UriTarget'
        description: Target a specific uri
      - $ref: '#/components/schemas/UnixTarget'
        description: Target a specific unix socket
    UnixTarget:
      type: object
      required:
      - UnixPath
      properties:
        UnixPath:
          type: string
      additionalProperties: false
    UpstreamTarget:
      type: object
      description: Config for targeting a cargo or a vm
      required:
      - Key
      - Port
      properties:
        Key:
          type: string
          description: The key of the cargo or the vm to target
        Port:
          type: integer
          format: int32
          description: The port of the cargo or the vm to target
          minimum: 0
        Path:
          type:
          - string
          - 'null'
          description: The http path to target when using http
        DisableLogging:
          type:
          - boolean
          - 'null'
          description: Disable logging for this target
        Ssl:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/ProxySsl'
            description: SSL configuration for this target
      additionalProperties: false
    UriTarget:
      type: object
      required:
      - Uri
      properties:
        Uri:
          type: string
          description: Uri to target
      additionalProperties: false
    UrlRedirect:
      type: string
      enum:
      - MovedPermanently
      - Permanent
      - Temporary
tags:
- name: Rules
  description: Rules management endpoints.
