name: Tests

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu_test:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: llvm-tools-preview
    - uses: actions/cache@v3
      with:
        path: ./target/llvm-cov-target
        key: llvm-cov-key
    - uses: actions/cache@v3
      with:
        path: ./fake_path/var/lib
        key: image-and-container-key
    - uses: Swatinem/rust-cache@v2
    - uses: davidB/rust-cargo-make@v1
    - uses: taiki-e/install-action@cargo-llvm-cov
    - uses: taiki-e/install-action@nextest
    - name: Create user
      run: sudo useradd -U nanocl && sudo usermod -aG nanocl $USER
    - name: Ci file perm
      run: >-
        sudo chown nanocl:nanocl /run/docker.sock;
        sudo chmod 777 /run/docker.sock;
        sudo mkdir -p /etc/nanocl;
        sudo chown nanocl:nanocl /etc/nanocl;
        sudo chmod 777 /etc/nanocl;
    - name: Setup
      run: >-
        newgrp nanocl;
        echo "docker_host: /run/docker.sock" > /etc/nanocl/nanocl.conf;
        sudo chmod 777 -R /etc/nanocl;
        sudo chown nanocl:nanocl /run/docker.sock;
        ls -l /run/docker.sock;
        cargo run setup && sleep 5 && sudo chmod 777 -R /run/nanocl;
    - name: Run tests
      run: cargo make test
